@baseUrl=http://localhost:3000

### --------------------------------------------
### Encrypt helper
# -------------- Pre Script -------------------------

POST {{baseUrl}}/api/cpps/encrypt

{
  "message":"Success",
  "data":{ 
    "ppo_id": "MG/11xx",
    "ppo_no": "MG/11xx"
  }
}

# -------------- Post Script -------------------------


### Decrypt helper
POST {{baseUrl}}/api/cpps/decrypt

{"payload": "gAAAAABqvO6dPIqUvEQwiB5i7MMKA1RkFQvsmWdKakGgAJP4uMN7BieSXiSBZt9rZwgTJlV-7W2D_gIdZAmpXDWYblx111rKr3G9lTiZZsa_NcLUynQDBT9fIdtXJSdjcqJyNYjlNC9tkWOIIJH48pqdJKuwt3arGs1nstsSDRGNDLTYvGczJV_1w1_NgH-dq5Nds_U0AwcynGcF5wARwlZOkqGaX2miLcwpOeJ67-aMxc6LzxEBnA_8gbCe-TUUQG_ziM4i5k_q09V_ELcOBDf9mRlRNoOchQWeqUkcKxzSbQechwPXTrYwYAJfVHeOOX_8Hrp3Kiy5iQTjcGBuDFDMsLSvf08TnQgJSEZKp-drh0qOMqVfL4M="}


### format-password helper
POST {{baseUrl}}/api/cpps/format-password

{
  "password": ""
}

### echo
POST {{baseUrl}}/api/echo

{ 
  "url":"/dlc",
  "status_code":200,
  "data":"gAAAAABqugsaQW_X9E-7WMuuV7OSEunPjXS51nk5AZ-yarGYRkcXbwqMTUW8GWxpm3XFTBQ4nE0ZMEwuVVEIiL-RChHYGvaOon6U7fgUAPCTh14mJ7Wr4XxXozKl8qhBGogkvv1Ph_udoQ44gobQLbKoH_ng8W2mNNiMe-LKjUruCCA6hAvFgXw="
}

###
GET {{baseUrl}}/api/echo
