@baseUrl=http://192.168.1.5:3000

### ============================================================
### CPPS Helpers
### ============================================================

### Encrypt
POST {{baseUrl}}/api/cpps/encrypt
Content-Type: application/json

{
    "token": "adsfasdfadsfasdfafdasdf",
    "app_exp": "2027-09-15",
    "bank_accno": "000000000000",
    "dob": "1962-04-18",
    "gender": "M",
    "member_id": "TEST-MEMBER-001",
    "mtype": "P",
    "pclass": "Regular",
    "pclass_cd": "01",
    "photo": null,
    "pname": "Test Pensioner",
    "ppo_id": "TEST-PPO-001",
    "ppo_no": "TEST-PPO-001",
    "ptype_cd": "01",
    "rela": "Self",
    "trea_code": "SHL",
    "treasury_name": "Shillong Treasury",
    "pan_dob": "1962-04-18",
    "pan_no": "TESTPAN000",
    "height": "170",
    "mobile_no": "0000000000",
    "comty_cd": "01",
    "marital_cd": "M",
    "email": "test@example.com"
} 

### Decrypt
POST {{baseUrl}}/api/echo/decrypt?write=true
Content-Type: application/json

{
  "payload": ""
}

### Format Password
POST {{baseUrl}}/api/cpps/format-password
Content-Type: application/json

{
  "password": ""
}


### ============================================================
### Echo
### ============================================================

### Create Echo
< {%
   request.variables.set('RAW_BODY', JSON.stringify({
     username: request.environment.get('PPO_NO'),
     password: request.environment.get('FORMAT_PASSWORD')
   }));
   require("./scripts/enc-req.http.js");
%}

POST {{baseUrl}}/api/echo
Content-Type: application/json

{
  "url": "/user",
  "status_code": 200,
  "data": "{{ENC_PAYLOAD}}"
}

### Get Echo

GET {{baseUrl}}/api/echo/user

# ------------ Post-script -------------------
> {%
   require("./scripts/dec-res.http.js");
%}
