@baseUrl=http://192.168.1.5:3000

### ============================================================
### CPPS Helpers
### ============================================================

### Encrypt
POST {{baseUrl}}/api/cpps/encrypt
Content-Type: application/json

{
    "token": "adsfasdfadsfasdfafdasdf",
    "app_exp": "2027-09-15",
    "bank_accno": "000000000000",
    "dob": "1962-04-18",
    "gender": "M",
    "member_id": "TEST-MEMBER-001",
    "mtype": "P",
    "pclass": "Regular",
    "pclass_cd": "01",
    "photo": null,
    "pname": "Test Pensioner",
    "ppo_id": "TEST-PPO-001",
    "ppo_no": "TEST-PPO-001",
    "ptype_cd": "01",
    "rela": "Self",
    "trea_code": "SHL",
    "treasury_name": "Shillong Treasury",
    "pan_dob": "1962-04-18",
    "pan_no": "TESTPAN000",
    "height": "170",
    "mobile_no": "0000000000",
    "comty_cd": "01",
    "marital_cd": "M",
    "email": "test@example.com"
} 

### Decrypt
POST {{baseUrl}}/api/echo/decrypt?write=true
Content-Type: application/json

{
  "payload": ""
}

### Format Password
POST {{baseUrl}}/api/cpps/format-password
Content-Type: application/json

{
  "password": ""
}


### ============================================================
### Echo
### ============================================================

### Create Echo
POST {{baseUrl}}/api/echo
Content-Type: application/json

{
  "url": "/user",
  "status_code": 200,
  "data": "gAAAAABqpr31DgSvrhJl5imrarrh8cv2oFNAG6Pumdtu-x-PFyTf6JY3fUMGOktoJm6oCTWvODjh_c_2C4NNjVArE-nyNqiL4KiPhH8fCPZOXirZ1gcO_uvZdnC_qTGVabpMvruZ7tNYIkn43KTXowbV_UWmaX6hvOXxc9sq9Km2ldUlijLIwPDuSaHpvpLlM4Mn963tRwiB7uEnly73MwHuYqlmvJibHMYm86eeXiiS1k5Br8HLVdkrpx-0p6pGmhwoO_oKsIxPSzfX5xnCTCo_Km8YkHc0xodSXhS-LcQd6SjIKc5BAcyYVRbAAhBth0UuyNbnLktOaihhzKZBhyE7RN2_i1-G4_6f0IuutvXHAbIM4yJjNUAFYy_3_0ESQGaySdnzwnUH6t1rxAQbT1chFylwn1jWj8rSrlEFhezTikCxycoroZJzdF9_M2pYc0-ubTCYH41L4ght2cPUeiEYJ2u_nNA4oK3CfxDP7sdvarvU9skzPRVkf_fMUihgvwmRD5WkeoYiXcjLmIFzzHskfYCYkoZJxbbd5A4xA7KQiDMPjQgELx1gzqfkS3wk23V8tEZR-4IZsz22zUw6csC91B3lfjWkC3Yd9LTA9iH0fKQPm0vttkKJutYpeg0tTpeVB87iKjPYAOG21Er1OrFpIHsqAe631SFmxGozXgG6cumBngGXcZOM1cT5gePM9uoUh5RzZMXdwhivrw9Hia-TEhVznMoUecb--m-c9vFvnVkim_vvdrQ="
}

### Get Echo
GET {{baseUrl}}/api/echo/user

# ------------ Post-script -------------------
> {%
   require("./scripts/dec-res.http.js");
%}
